### ✅ 회원가입
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "1234",
  "nickname": "테스터"
}

###

### ✅ 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "1234"
}

###

### ✅ 로그아웃
DELETE http://localhost:8080/users/logout


###

### ✅ 전체 유저 조회
GET http://localhost:8080/users/all
Accept: application/json
Cookie-jar: session

###

### ✅ 특정 유저 조회
GET http://localhost:8080/users/1
Accept: application/json
Cookie-jar: session

###

### ✅ 프로필 수정
PUT http://localhost:8080/users/1
Content-Type: application/json
Cookie-jar: session

{
  "email": "newemail@example.com",
  "nickname": "테스터변경"
}

###

### ✅ 비밀번호 변경
PATCH http://localhost:8080/users/1
Content-Type: application/json
Cookie-jar: session

{
  "oldPassword": "1234",
  "newPassword": "12345"
}

###

### ✅ 회원탈퇴
DELETE http://localhost:8080/users/1
password: 12345
Cookie-jar: session

###

### ✅ 게시글 생성
POST http://localhost:8080/feeds
Content-Type: application/json
Cookie-jar: session

{
  "title": "첫 번째 게시글입니다.",
  "contents": "안녕하세요."
}

###

### ✅ 게시글 전체 조회
GET http://localhost:8080/feeds
Accept: application/json
Cookie-jar: session

###

### 페이지 0 (첫 페이지)
GET http://localhost:8080/feeds?page=0
Accept: application/json

### 페이지 1 (두 번째 페이지)
GET http://localhost:8080/feeds?page=1
Accept: application/json

### 페이지 2 (세 번째 페이지)
GET http://localhost:8080/feeds?page=2
Accept: application/json

###

### ✅ 게시글 단건 조회
GET http://localhost:8080/feeds/1
Accept: application/json
Cookie-jar: session

###

### ✅ 게시글 수정
PUT http://localhost:8080/feeds/1
Content-Type: application/json
Cookie-jar: session

{
  "title": "첫 번째 게시글 - 수정됨",
  "contents": "내용 수정"
}

###

### ✅ 게시글 삭제
DELETE http://localhost:8080/feeds/1
Cookie-jar: session

###

### ✅ 댓글 생성
POST http://localhost:8080/comments
Content-Type: application/json
Cookie-jar: session

{
  "feedId": 1,
  "contents": "댓글입니다."
}

###

### ✅ 댓글 수정
PUT http://localhost:8080/comments/1
Content-Type: application/json
Cookie-jar: session

{
  "contents": "댓글을 수정합니다."
}

###

### ✅ 댓글 삭제
DELETE http://localhost:8080/comments/1
Cookie-jar: session

###

### ✅ 게시글 좋아요 등록
POST http://localhost:8080/likes/feeds/1
Cookie-jar: session

###

### ✅ 게시글 좋아요 취소
DELETE http://localhost:8080/likes/feeds/1
Cookie-jar: session

###

### ✅ 댓글 좋아요 등록
POST http://localhost:8080/likes/comments/1
Cookie-jar: session

###

### ✅ 댓글 좋아요 취소
DELETE http://localhost:8080/likes/comments/1
Cookie-jar: session
